public class checkDatatypes {
    public void MethodBoolean(){
        Boolean checkBoolean =true;
        system.debug (checkBoolean);
    }
    public void MethodInteger(){
        Integer varfirst= 1;
        Integer varsecond= 2;
        system.debug(varfirst);
        system.debug(varsecond);
    }

    public void Stringmethod(){
        String varname= 'Name';
        String var2name= 'Amy';
        system.debug(varname);
        system.debug(var2name);
    }
}